runelite.aiweaponreviewplugin=false
runelite.unforgeitemmakerplugin=false
runelite.unforgenpcbossplugin=false
runelite.unforgequestmakerplugin=false
runelite.unforgeshopmakerplugin=false
runelite.unforgeweaponpreviewplugin=false
runelite.uibuilderplugin=false
runelite.devtoolsplugin=false
runelite.discordplugin=false
runelite.crowdsourcingplugin=false
runelite.hiscoreplugin=false
runelite.grandexchangeplugin=false
runelite.partyplugin=false
runelite.cluescrollplugin=false
runelite.barbarianassaultplugin=false
runelite.blastfurnaceplugin=false
runelite.blastmineplugin=false
runelite.corpplugin=false
runelite.driftnetplugin=false
runelite.herbiboarsplugin=false
runelite.hunterplugin=false
runelite.implingsplugin=false
runelite.kingdomplugin=false
runelite.kourendlibraryplugin=false
runelite.motherlodeplugin=false
runelite.mtaplugin=false
runelite.pestcontrolplugin=false
runelite.raidsplugin=false
runelite.wintertodtplugin=false
runelite.zalcanoplugin=false
